<div>
<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Selamat Pagi!</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Halo salam kenal, saya Ana Trisni dari&nbsp;CV. Kreasi Muda Indonesia&nbsp;yang berlokasi di Mojosongo, Jebres, Surakarta. Kami ingin memperkenalkan salah satu&nbsp;</span><em>brand</em><span style="background-color:transparent; font-size:11pt">&nbsp;kami yaitu&nbsp;Malika Wallart&nbsp;yang berfokus dalam produksi hiasan dinding yang keren.</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Kami sebagai penyedia hiasan dinding berniat untuk melakukan kolaborasi antara ::full_name:: dengan Malika Wallart. Tujuannya adalah menjadikan ruangan hotel jadi lebih </span><em>fresh</em><span style="background-color:transparent; font-size:11pt"> dan menjadikan penggunjung lebih betah.&nbsp;&nbsp;</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Kami memiliki produk beragam seperti hiasan dinding Laser Cut dan Leather yang keduannya dapat disesuaikan dengan tipe dari ruangan dari ::full_name::. Ruangan standar bisa diberikan </span><em>hiasan dinding&nbsp;</em><span style="background-color:transparent; font-size:11pt">Laser Cut dan Superior Room, Deluxe Room atau Suite Room bisa dengan Laser Cut atau Leather. Anda bisa cek beberapa produk kami&nbsp;</span><a href="::link::=https://malika.id/product-category/produk/" target="_blank">disini</a><span style="background-color:transparent; font-size:11pt">.</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Apabila jenis produk kami diatas tidak sesuai dengan keinginan ::full_name::, kami juga bisa melayani produk&nbsp;</span><em>custom</em><span style="background-color:transparent; font-size:11pt">&nbsp;hiasan dinding dengan menambahkan logo perusahaan anda atau disesuaikan dengan kebutuhan dari masing-masing ruangan ::full_name::.</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="font-size:11pt">Apabila </span><span style="background-color:transparent; font-size:11pt">::full_name:: </span><span style="font-size:11pt">berminat untuk mengetahui produk&nbsp;Malika Wallart&nbsp;lebih detail bisa menghubungi via&nbsp;</span><a href="http://#" target="_blank">Whatsapp Kami</a><span style="font-size:11pt">.&nbsp;Selain itu dapat berkunjung ke&nbsp;workshop&nbsp;kami di&nbsp;Jl. Slamet Raya, Tawangsari, RT.01 RW.34, Mojosongo, Jebres, Surakarta, Jawa Tengah, 57127, Indonesia. Anda bisa klik di bawah untuk mengarahkan langsung ke&nbsp;</span><em>workshop</em><span style="font-size:11pt">&nbsp;kami.</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Besar harapan kami dapat menjalin kerjasama yang saling menguntungkan dengan ::full_name::. Jika dibutuhkan, kami akan dengan senang hati memberikan informasi lebih lanjut.</span></span></p>

<p dir="ltr" style="text-align:justify"><span style="background-color:transparent; color:#000000; font-family:Calibri,sans-serif; font-size:11pt"><span style="background-color:transparent; font-size:11pt">Terimakasih atas perhatiannya. Kami menantikan kabar baik selanjutnya.</span></span></p>

<div>&nbsp;</div>
</div>
