<p><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Halo Bapak/ Ibu Pejabat Pembuatan Komitmen</span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Sebelumnya, izinkan kami memperkenalkan diri</span><span style="font-size:12.0pt">. Kami dari <a href="https://malika.id/"><span style="color:#90c42f"><strong><u>Malika Wallart</u></strong></span>.</a> Kami merupakan perusahaan produsen hiasan dinding dan souvenir terbesar di Indonesia yang telah berdiri sejak tahun 2017.</span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Produk unggulan kami adalah <strong>Hiasan Dinding</strong> dan <strong>Souvenir </strong>mulai dari<strong> Trofi, Plakat dan Vandel </strong>dengan berbagai bahan muali dari kayu, kulit sapi, akrilik dan photo paper dengan berbagai ukuran. </span><span style="font-size:12.0pt">Sebelumnya, kami ingin mengucapkan semoga kebahagiaan, keceriaan dan keselamatan selalu menyertai kita semua </span><span style="font-size:12.0pt"><span style="font-family:Wingdings">J</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Tahukah jika pemberian souvenir yang menarik bisa memberikan efek yang positif baik di hubungan bisnis dan juga menunjukan eksistensi bagi suatu instansi agar tidak dipandang sebelah mata. </span><span style="font-size:12.0pt">Untuk menanggulangi masalah tersebut, </span><strong><span style="font-size:12.0pt">Malika Wallart</span></strong><span style="font-size:12.0pt"> menawarkan produk spesial yang bertajuk </span><strong><span style="font-size:12.0pt">Souvenir Malika Wallart</span></strong><span style="font-size:12.0pt">. Produk kami dapat </span><span style="font-size:12.0pt">memenuhi kebutuhan</span> <strong><span style="font-size:12.0pt">SOUVENIR UNIK </span></strong><span style="font-size:12.0pt">mulai dari trofi atau piala, vandel dan plakat. </span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Souvenir dari Malika Wallart memiliki keunggulan daripada competitor lainnya, seperti:</span></span></span></p>

<ol>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">BISA CUSTOM</span></strong><span style="font-size:12.0pt"> desain dan bahan baku sesuai dengan kebutuhan kalian.</span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Bisa kami </span><strong><span style="font-size:12.0pt">KIRIM KE SELURUH INDONESIA</span></strong><span style="font-size:12.0pt">.</span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">PACKAGING YANG KEREN</span></strong><span style="font-size:12.0pt"> dan aman sampai tujuan</span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Menggunakan </span><strong><span style="font-size:12.0pt">BAHAN BAKU BERKUALITAS</span></strong><span style="font-size:12.0pt"> unggul</span></span></span></li>
</ol>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Jikalau Bapak/ Ibu tertarik dengan </span><span style="font-size:12.0pt">souvenir dari Malika Wallart, </span><span style="font-size:12.0pt">kami akan memberikan promo spesial</span><span style="font-size:12.0pt"> hanya untuk kalian</span><span style="font-size:12.0pt">.</span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Dengan membeli </span><strong><span style="font-size:12.0pt">Souvenir Malika Wallart</span></strong><strong><span style="font-size:12.0pt">, </span></strong><span style="font-size:12.0pt">kalian akan mendapatkan</span> <strong><span style="font-size:12.0pt">POTONGAN HARGA SEBESAR 5%!</span></strong></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Untuk informasi lebih lanjut</span></strong><span style="font-size:12.0pt">, </span><span style="font-size:12.0pt">silahkan</span><span style="font-size:12.0pt"> cek di website </span><strong><span style="font-size:12.0pt">malika.id</span></strong><span style="font-size:12.0pt"> atau hubungi kami ke nomer </span><a href="https://api.whatsapp.com/send?phone=6281266006161&amp;text=Halo%20Malika,%20pesannya%20gimana%20ya?"><strong><span style="font-size:12.0pt">0812-6600-6161</span></strong></a><span style="font-size:12.0pt">. Jangan sungkan-sungkan kalau kalian hanya ingin menanyakan harga ataupun bertegur sapa kepada kami, karena kami selalu melayani dengan sepenuh hati.</span> <span style="font-size:12.0pt">Mungkin itu saja yang bisa kami sampaikan, selamat beraktivitas dan bersitirahat. </span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Kami tunggu kabar baik dari kalian.</span> </span></span></p>

<p style="text-align:justify">&nbsp;</p>
